### ISSUE TITLE
output devices only?

### ISSUE THREAD

**Issue by micha-kaiser** [nvdweem/PCPanel#10]
I am not sure if I overlooked this, but right now, pcpanel only seems to list output devices. I'd like to control my USB microphone as well. 

Is this (somehow) possible?

**Comment by nvdweem** [comment]
Not sure if you are using Windows/Linux and which version, but at least on Windows there should be the option to control both input and output devices:
![msedge_6v7ZAzhJG6](https://user-images.githubusercontent.com/830783/188271233-04278cf5-6c86-403d-9409-ed5b4f730d2a.gif)

Windows does not offer per-process volume controls for input devices so that isn't possible. It should be that everywhere where you pick a device it also lists the input devices. The 'Default device' option controls the default output, not the default input.

**Comment by micha-kaiser** [comment]
Sorry, I am sorry. I use Linux (ubuntu 22.04)

**Comment by micha-kaiser** [comment]
I tried to add the corresponding index entry from `pacmd list-sinks` to profiles.json manually but this does not seem to work.

**Comment by nvdweem** [comment]
I'm not very familiar with Linux audio, but iirc, sinks are outputs and sources are supposed to be inputs. I think the software currently only lists the outputs.

I'll see if I can add the sources as well and make them controllable.

**Comment by nvdweem** [comment]
My Linux VM is super slow at the moment so I'm not able to test it properly, but the new Pre-release snapshot should include input devices. The devices should now also have an in/out postfix in their name.

**Comment by micha-kaiser** [comment]
Niels,

will try this later. Thanks a lot!

**Comment by micha-kaiser** [comment]
Yes, sinks are outputs, sources are inputs

**Comment by micha-kaiser** [comment]
![Bildschirmfoto_2022-09-04_19-05-59](https://user-images.githubusercontent.com/11025045/188325138-2dbe384d-ee89-4659-b802-815b8c14841f.png)

Works like a charm. Thanks a lot!

**Comment by nvdweem** [comment]
You are welcome, Happy to see that the Linux support is actually being used :).
