### ISSUE TITLE
No active profile set

### ISSUE THREAD

**Issue by JustinLR** [nvdweem/PCPanel#12]
**Describe the bug:**

Every few reboots of my PC, the software loses all of it's settings for some reason. Even after reinstalling Windows, trying different versions of the software, and trying different profiles it still happens. Checked the logs and found this:
```
 2022-10-26 07:56:35.294  INFO 4984 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Started application in 1.659 seconds (JVM running for 2.21)
 2022-10-26 07:56:35.306  INFO 4984 --- [JavaFX Application Thread] com.getpcpanel.MainFX                    : Starting v1.5
 2022-10-26 07:56:35.388  INFO 4984 --- [JavaFX Application Thread] com.getpcpanel.hid.DeviceScanner         : Starting HID services.
 2022-10-26 07:56:35.482  INFO 4984 --- [JavaFX Application Thread] com.getpcpanel.hid.DeviceScanner         : Enumerating attached devices...
 2022-10-26 07:56:35.482  INFO 4984 --- [hid4java event worker] com.getpcpanel.hid.DeviceScanner         : FOUND PCPANEL : HidDevice [path=\\?\hid#vid_0483&pid_a3c5#c&19d989a3&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, vendorId=0x483, productId=0xa3c5, serialNumber=5B43EB363832, releaseNumber=0x200, manufacturer=PCPanel Holdings LLC, product=PCPanel Pro 1.0, usagePage=0xffffff00, usage=0x1, interfaceNumber=-1]
 2022-10-26 08:07:10.987  INFO 17968 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Starting application using Java 17.0.1 on DESKTOP-6DH1HSU with PID 17968 (started by Justin Richards in C:\Users\Justin Richards\AppData\Local\PCPanel)
 2022-10-26 08:07:10.988  INFO 17968 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : No active profile set, falling back to 1 default profile: "default"
 2022-10-26 08:07:14.304  INFO 17968 --- [OBS Connection Starter] org.eclipse.jetty.util.log               : Logging initialized @5151ms to org.eclipse.jetty.util.log.Slf4jLog
 2022-10-26 08:07:14.417 ERROR 17968 --- [JavaFX-Launcher] com.github.kwhat.jnativehook             : Unable to extract the native library /com/github/kwhat/jnativehook/lib/windows/x86_64/JNativeHook.dll!
```

**Steps to reproduce:**

Unknown

**Expected behavior:**

To be fully functional without loss of settings.

**Additional context:**

OS: Windows 11 22H2 Build 22621.755
CPU: AMD Ryzen 9 5900X
RAM: 64GB

Software Version: v1.5

**Comment by nvdweem** [comment]
The 'No active profile set' you see in the log is not the profile in the application but a set of properties that the application uses. Unfortunately this log does not show anything wrong. Are there more logs that do show issues (if there is something logged it will probably be either in the log when the working situation was closed or when the broken situation just started).

I'll try and find a reason why this could be happening. I haven't seen this behavior before though.
Did this also happen in the original software or is it just this version?

**Comment by Justin092** [comment]
Unfortunately, there is nothing else in the logs aside from stuff like

> 	at com.getpcpanel.MainFX.init(MainFX.java:22) ~[pcpanel-1.5.jar:1.5]
> 	at javafx.graphics@18.0.2/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source) ~[javafx.graphics:na]
> 	at javafx.graphics@18.0.2/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source) ~[javafx.graphics:na]
> 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

This happened in the original software which is why I switched over to this version hoping it wouldn't happen. 

Not sure what causes it; I have attempted to track down the situation that causes, but it seems random. Sometimes it will keep the settings on reboot, and other times it won't.

**Comment by nvdweem** [comment]
The snippet you show is an error that occurred, it could be interesting to see the rest, but I'm expecting it to start with
```
java.lang.UnsatisfiedLinkError: Unable to extract the native library /com/github/kwhat/jnativehook/lib/windows/x86_64/JNativeHook.dll!
```
That is an error I still should fix but isn't causing the issue.

I would expect that there is something that is clearing files from your userprofile.
The original software places the save file in `%localappdata%\PCPanel Software\`, this version puts it in `%userprofile%\.pcpanel`

It's not a solution, but you could copy the `%userprofile%\.pcpanel\profiles.json` file so that you can restore it if it happens again. It should be enough to close the software, copy the file back and start it again.

When there is no save file there should be a line in the logging that states `No save file found, creating new one`, I'm a bit suprised that it isn't in your log.
When it happens, are there still logs from previous days?

**Comment by Justin092** [comment]
@nvdweem here's the latest log file, unfortunately I did not save the log files from before uninstalling/reinstalling the software. But I linked what I have, and will continue trying to replicate the issue, and upload the corresponding log files. So far, I have been unable to replicate it, of course. 

[logging.log](https://github.com/nvdweem/PCPanel/files/9888133/logging.log)

I uninstalled the original PCPanel software completely so the only thing I have of that is when I installed it temporarily to try and recreate the issue.

[logfile.txt](https://github.com/nvdweem/PCPanel/files/9888163/logfile.txt)

I understand none of this may be helpful since the issue hasn't occurred since I uninstalled/reinstalled the software, so I will try and recreate the issue, and upload log files as it happens. Thanks for all the help :)

**Comment by Justin092** [comment]
Ok, so yesterday 10/29/2022 I did not use my computer at all, Friday I used my PC normally, and today at 2:00PM I turned on my PC and checked PCPanel for the heck of it. It lost it's settings again. 

This time, I have not messed with it since, and just left it as is, so hopefully the log will have something helpful this time around.

[logging.log](https://github.com/nvdweem/PCPanel/files/9896476/logging.log) Todays log

[logging.log.2022-10-25.0.gz](https://github.com/nvdweem/PCPanel/files/9896485/logging.log.2022-10-25.0.gz)
[logging.log.2022-10-26.0.gz](https://github.com/nvdweem/PCPanel/files/9896486/logging.log.2022-10-26.0.gz)
[logging.log.2022-10-27.0.gz](https://github.com/nvdweem/PCPanel/files/9896487/logging.log.2022-10-27.0.gz)
[logging.log.2022-10-28.0.gz](https://github.com/nvdweem/PCPanel/files/9896488/logging.log.2022-10-28.0.gz)
[logging.log.2022-10-29.0.gz](https://github.com/nvdweem/PCPanel/files/9896484/logging.log.2022-10-29.0.gz)

I have also attached the previous days logs just in case those would be helpful.

**Comment by nvdweem** [comment]
I had expected it to log that the settings file wasn't found but that isn't in there, so the file should be there. Another option would have been that the pcpanel somehow got a different serialnumber which would cause the software to see it as a new device, but looking at the older logs that didn't happen either...
Other than the startup taking way longer than other runs I see no difference, and even that wouldn't be a reason for the software to just not load the settings. There is an error on 10/29/2022 at 15:16 when the software was shutting down (it seems that the pc was started that day), but on shutdown there shouldn't be any saving.

I have no idea what could be causing this. Anything I can think of should either trigger an exception (anything structurally wrong with the profiles.json should do that) or trigger logging about the file not being there.
I'd almost expect some backup-tool to put the profiles.json back to some empty profile.

When it happens, could you open the profiles.json (or attach it) to see if it's empty or corrupted? It should start with something like:
```
{
  "devices" : {
    "5B43EB363832" : {
      "displayName" : "pcpanel1",
      "profiles" : [ {
```
If it doesn't have that then there is something strange going on, if it does start like that, try restarting the software to see if it does get read correctly then.

**Comment by Justin092** [comment]
Here's the profiles.json that is currently in the pcpanel folder. (Had to save it to a .txt file as GitHub wouldn't allow the upload of .json)

[profiles.txt](https://github.com/nvdweem/PCPanel/files/9897259/profiles.txt)

**Comment by nvdweem** [comment]
The profile seems fine, so it's not that it gets corrupted.

Did the profile get fixed after a restart of the software/pc or did it fix itself while everything was running? Both situations are weird, but the second one makes even less sense :).

**Comment by Justin092** [comment]
Hard to say, I just noticed it went back to normal after I opened the .json file. So maybe a restart did it, but impossible to say at the moment.

I keep an eye open and if the settings disappear again, I will check the json file to see what happens.

**Comment by JustinLR** [comment]
Ok, so just had this happen again today after my computer was asleep for about 20 minutes. I attached the profiles file in hopes it may show something.

Thankfully I backed up the profiles file before this happened, so I was just able to copy/paste and get all of my settings back. Kinda annoying to have to overwrite the file every time this happens but if I have to, then I have to. Better than nothing.

[profiles.txt](https://github.com/nvdweem/PCPanel/files/9971379/profiles.txt)

Logs from today and yesterday:
[logging.log.2022-11-08.0.gz](https://github.com/nvdweem/PCPanel/files/9971390/logging.log.2022-11-08.0.gz)
[logging.log](https://github.com/nvdweem/PCPanel/files/9971391/logging.log)

**Comment by nvdweem** [comment]
I've tried to figure out what could be causing this and so far I still haven't found a single reason for how this could happen.
I would have expected something wrong with your disk, but losing settings after resuming from sleep wouldn't be explained by that. So I don't know if there is anything I can currently do to help.

**Comment by JustinLR** [comment]
Sorry about that, forgot about this for a while as I don't use GitHub much. As far as I can tell, it seemed to be due to WaveLink audio control software. Not sure exactly what caused it, but some changes must have taken place with WaveLink to change or remove the virtual cables therefore causing PCPanel not to see it. After an update to WaveLink I have not had any issues since November, so it seems to be resolved.
