### ISSUE TITLE
[Toggle Device] Can't drag a sound device

### ISSUE THREAD

**Issue by SebastienBenazet** [nvdweem/PCPanel#2]
Hi!

I'm unable to drag and drop or double clic a sound device in the "Toggle Device" section.
![image](https://user-images.githubusercontent.com/6958576/174440004-2bfd4f39-4efb-44b7-848c-fe513edf7a51.png)

My use of this feature is to switch between Speakers and Headset on a single Knob press.

Thanks for your hard work!

**Comment by nvdweem** [comment]
This should now be fixed.

**Comment by SebastienBenazet** [comment]
Drag and drop is now working 👍🏻, but the actual action of switching between devices doesn't work on knob clic.

Here is the message I get in the log file :
2022-06-18 21:49:41.099 ERROR 3236 --- [Command Handler Thread] c.g.c.c.CommandVolumeDefaultDeviceToggle : TODO

**Comment by nvdweem** [comment]
I probably should have actually tested. The functionality instead of just the drag and drop :)
I'll look into fixing the Todo tomorrow. Might be a good moment to check if I put more todos in the code ;)

**Comment by nvdweem** [comment]
The todo should now be implemented. I've tried to make it a bit smarter than just having a fixed order. If you manually change the output device (or do so through another button action) the order will continue from the current default device.

I also changed the UI a bit. I don't think it makes sense to combine input and output devices in the list so the list disables the output devices if you select an input device and the other way around. If this assumption is wrong please let me know because it will also mean that following the current default device can't be done because there would be multiple default devices :).

**Comment by SebastienBenazet** [comment]
It works perfectly well, thanks a lot! 🥇
