### ISSUE TITLE
[Music Control] Knob press not working on screensaver

### ISSUE THREAD

**Issue by SebastienBenazet** [nvdweem/PCPanel#3]
Hi, it's me again!

I'm using knob press for Spotify play/pause, next/previous track.
![image](https://user-images.githubusercontent.com/6958576/174746313-c3fbb53d-49bc-41a1-abd1-caba22f428df.png)

I'm also using [FLIQLO](https://fliqlo.com/) which is a screensaver on Windows.

When the screensaver is active, the play/pause and previous/next track doesn't work.

It's something that wasn't working in the official software and I was wondering if you could fix it maybe?

**Comment by nvdweem** [comment]
It seems that when the screensaver is running the media keys don't reach the application. My keyboard media keys also don't work (but they count as input so they do turn off the screensaver).

[I found a way to send the key events differently](https://github.com/moobsmc/spotify-controls/blob/master/Spotify.cpp), which does seem to work (and won't turn off the screensaver). The screen you posted now has an additional checkbox to send the using an alternative method.
I'm not entirely sure how Windows decides what to control but for me it seems to prefer Spotify over Chrome for some reason. If this doesn't work I can still try to get the window handle from the process instead of getting it using a non-unique window class.

**Comment by nvdweem** [comment]
Decided to take the effort to specifically control Spotify instead of possibly making it kinda random what gets controlled.
When the checkbox is enabled it should now really target only Spotify, not anything that happens to be Chromium.

**Comment by SebastienBenazet** [comment]
Wow, this will be a game changer as I mainly use my PCPanel Mini to control output source and Spotify but it was controling the media in focus. So when I was on Chrome with a youtube video, it would play/pause the video instead of Spotify.

Maybe this feature is very oriented to my personal use but I appreciate your effort!

I'll give it a try and let you know

**Comment by SebastienBenazet** [comment]
Ok, I tested the nex 1.4 Snapshot, it works perfectly with the screensaver, thanks!

I close this issue
