### ISSUE TITLE
New User Feedback

### ISSUE THREAD

**Issue by joshuacant** [nvdweem/PCPanel#40]
Hi, I wanted to share my experience as someone who, in the span of the last 12 days: learned that the PCPanel existed, purchased one, and discovered that it had both official and unofficial software.

It's very confusing that both softwares have the same name. At first I thought this was an old repo for the official software from the early prototyping days because the version number here is 1.6 and the official software is 2.2. In fact, I installed the 2.2 version first. It took seeing a few Reddit posts to realize that this is 3rd party software based on (not 100% sure about this) decompiling the Java package of the official version. 

I don't have any suggestions about how to resolve this, it's up to you if you even view it as a problem. I just wanted to let you know my experience. I've found this branch of the software to be the superior one and wish it had been clear from the start that it was different from the official download.

Thanks for everything you've done here. I'm more satisfied with my PCPanel that I would be if the official software was the only option.

**Comment by nvdweem** [comment]
I had expected that the distinction between the website and github would have been clear enough, but I see that that isn't always the case. Apart from people not being able to find this software due to it looking like an old version, there are probably also more reasons to prevent the confusion :).

I changed the readme and project description to be more clear about the points you mention. It now includes that:
- It's third party software
- It's community managed (even though 'community' currently is just me)
- The version numbers don't align

The software still has the same name (and I have no idea how to have a descriptive name that isn't just 'PCPanel software), but I'm hoping it's more clear that this software is different.

Also, nice to hear that the software is considered to be superior :)

**Comment by joshuacant** [comment]
Definitely superior! 

The only thing I can think of, that I've seen other projects do, is something like "OpenPanel - Alternative Software for PCPanel Devices" which is fairly common. I think one of the primary reasons is trademark stuff, but it's probably unlikely that the PCPanel guys are gonna bother with that sort of unpleasantness. 

Thanks so much for your time, both on the software and responding to me here.

**Comment by nvdweem** [comment]
I initially created an OpenPCPanel project where I started to rewrite the software from scratch, but figured that it would be too much work with very little benefit compared to decompiling and proceeding from there. But I thought that calling a decompiled version of software 'open' didn't feel right so I just went with PCPanel. For now I'm hoping that the changes that are made are clear enough :)

Thanks for sharing your experience.
