### ISSUE TITLE
Unable to change volume for foobar2000.exe 

### ISSUE THREAD

**Issue by AmbientWill** [nvdweem/PCPanel#5]
Pretty much that, the original version was able to modify the volume for this music player application but doesn't seem to work here. Thanks for all the hardwork btw, I love the fact that you added the option to add more than 2 processes on each knob/slider!

EDIT: Current using PCPanel Controller 1.4-SNAPSHOT

**Comment by nvdweem** [comment]
A new snapshot should be available in a few moments, but I'm currently at a LAN-party without my PCPanel so I haven't fully tested the change :)

The issue seems to be that foobar2000 adds a bunch of audio sessions and the one session that should actually trigger changes wasn't registered correctly. The fix should allow for multiple sessions for a single pid.
I'll test this more myself when I'm back home tomorrow, in the mean time you could check to see if the change works for you.

The fix is in the Windows sndctrl dll, so if I made a mistake the application will crash and just disappear without any warning :$.

**Comment by AmbientWill** [comment]
Thanks, it certainly seems to be working ATM. I'll let you know if there are any other issues as I'm testing. Didn't mean to bother you during your LAN-party but I hope you had fun and I appreciate what you do.

**Comment by nvdweem** [comment]
No problem, if it would have bothered me I would have left the fix for after the weekend ;).
