### ISSUE TITLE
Cant find .msi file & slider flickering

### ISSUE THREAD

**Issue by Maddias** [nvdweem/PCPanel#6]
Not sure if this is the right place where to post this, but anyway.
In the entire .zip file i cant find a .msi file. Or is that not where i was supposed to look?
Also one more question, with the original software the readings for the slider flicker up and down slightly, it makes the sliders unusable.

**Comment by nvdweem** [comment]
You probably clicked the Code button and downloaded the zip from there? Those are the sources and they don't contain the release.

The releases are behind the 'Releases' button on the main page: https://github.com/nvdweem/PCPanel/releases

All releases have `Assets` and that list should include the msi:
![image](https://user-images.githubusercontent.com/830783/176675076-ed11b672-cddf-45fb-aeb5-d656c20ece8d.png)

**Comment by nvdweem** [comment]
How the sliders are read isn't different in this version so I think you might have the same issue here.

Do your sliders just go up and down constantly or do they slowly drift? If it's just up or down I might be able to figure out a way to ignore changes that are less than a certain value but if there is a drift then I'm not sure how that could be done in a useful way.
Is it possible to screen-grab what it looks like in the software? That could help me reproduce the issue to try and fix it.

It would probably be best to try and have the device replaced but with the lack of support I don't think that is a real option.

**Comment by nvdweem** [comment]
Screengrabbing is just grabbing the screen, screenshotting or recording, so the video is great :).

The slider seems to jump and immediately go back so I would have expected the audio to just jump to the new volume and back to the old but that also doesn't seem to happen. If that would happen it might be short enough to not notice the change. That is something that might work better in my version but I think it will still jump around.

I'm expecting it to be a hardware issue but it looks like it should be possible to mitigate it by adding a small delay before actually setting the volume. I'll try to look into it soon.

**Comment by Maddias** [comment]
Ive installed your version, the problem is still there but doesn't seem be as bad. but on the old version it also worked fine sometimes for a few hours just for it to go crazy again after that.

**Comment by nvdweem** [comment]
Without having an actual faulty device it's somewhat guessing at how to fix the behavior, but I implemented a possible fix.

I've assumed that when the slider flickers that it goes to a different value and back within a few milliseconds so I added an option in the settings:
![image](https://user-images.githubusercontent.com/830783/176763155-b50dbd2a-e595-4928-ab49-57111cc3c2d4.png)
![image](https://user-images.githubusercontent.com/830783/176763236-5ec37fbf-3357-4eeb-b71b-fdafe8bc63ba.png)

I tested this with a fake twitching mechanism that had 0 delay, so for me 10ms was sufficient, You might have to set it higher for it to do anything.

This will then be used as a debounce time for detecting twitching. If 2 changes follow quickly after each other and the second change is the initial value then both changes will be cancelled.
If the twitching behavior switches between more than 2 values you will see no difference in behavior but I think the video showed that it goes from x to y back to x.

If this doesn't solve the issue I might have to build a version with more logging so that the actual values are written to a file you can then send back to help me identify what is happening.

The updated version should be the 1.5-SNAPSHOT version, you can find it here: https://github.com/nvdweem/PCPanel/releases

**Comment by Maddias** [comment]
Ok thanks ill see if it works

**Comment by nvdweem** [comment]
I'll try to add a rolling average next (might take a few days), but if it the flickering isn't constant it will still trigger volume changes. The changes might be minor enough to not notice it as much but it would still be better to exclude the outliers completely.

**Comment by Maddias** [comment]
Yes i understand it won't be completely gone this way, but it seems impossible to exclude completely

**Comment by nvdweem** [comment]
The release should now be updated with an attempt at getting rolling averages. The Experimental tab now has an additional field for that. You should be able to reset the other field to empty or 0 and set the new one to any value. The value will determine the rolling window timeout. Having a rolling window will make the device less responsive (it will take the window length to actually get to the value) but it should smooth out the flickering.


I'm still interested in how the device is misbehaving. To determine that you should be able to add a file: `%localappdata%\PCPanel\application.properties` with the content of
```
logging.level.com.getpcpanel.hid.DeviceCommunicationHandler=debug
```

Doing that should add logging lines in the `%userprofile%\.pcpanel\logs\logging.log` with lines like
```
2022-07-01 22:57:58.683 DEBUG 49132 --- [HIDHandler] c.g.hid.DeviceCommunicationHandler       : < KnobRotateEvent[serialNum=5D43E1353833, knob=5, value=217, initial=false]
```
Those should show what the device is reporting.

If you could run the application like that for a little while and then send the log I might be able to figure out a better workaround. Having either of the preventing options turned on makes the log not useful so if you are willing to do this, please turn those off.

**Comment by Maddias** [comment]
I cant find this path
%localappdata%\PCPanel\application.properties

**Comment by Maddias** [comment]
[logging.log](https://github.com/nvdweem/PCPanel/files/9032082/logging.log) at path C:\Users\(username)\.pcpanel\logs
This is the only file i can find that updates everytime i close pcpanel.

I created a text file with the string of code you told me.
Then manually tried it with .properties .gz and .log but none of them seemed to change anything.

**Comment by nvdweem** [comment]
`%localappdata%\PCPanel\` is supposed to be the installation directory but from the logfile I see that it's installed at `D:\Program Files (x86)\Pcpanel github` for you, that means that the `application.properties` file should be at `D:\Program Files (x86)\Pcpanel github\application.properties`

The file can also be created by doing `Windows+R`, running `cmd` and then executing
```
echo logging.level.com.getpcpanel.hid.DeviceCommunicationHandler=debug > "D:\Program Files (x86)\Pcpanel github\application.properties"
```
The file should then be created in the installation folder and after a restart the logfile should start filling up with what the device is sending.

Also, did the last update improve the behavior of the sliders when you do set the rolling average?

**Comment by Maddias** [comment]
[logging.log](https://github.com/nvdweem/PCPanel/files/9032768/logging.log)
Here is the file, it only seems to log the knob values though, or am i missing something?

The rolling average did help, but the issue wasnt as bad when testing as it was before posting.
sometimes it's fine for weirdly long amounts of time to just come back again later.

**Comment by nvdweem** [comment]
> Here is the file, it only seems to log the knob values though, or am i missing something?

There are 2 types of events, ButtonPressEvents which are the clicks on the buttons and KnobRotateEvents which are both the rotating of the knobs and the sliding of the sliders. The lines indicate which knob was rotated, on a Pro 0-4 are Button 1-5 and 5-8 are slider 1-4.

When I look at slider 2 (knob=6), it reported 1500 updates in 3 minutes (~6000 for all sliders). Unless you are actually moving the sliders, this number should be 9 (initial value for all knobs and sliders) so there definitely seems to be something wrong with the device. Having to process all the events also means that the software needs to do something which will also increase the cpu load.

The distinct values and their counts for the sliders/knobs are these:
```
knob={value=count, ...}
2={64=18, 65=38, 66=30}
5={122=11, 123=424, 124=748, 125=439, 126=169, 127=3}
6={160=164, 161=6, 156=7, 157=340, 158=652, 159=349}
7={144=614, 145=374, 146=16, 142=52, 143=318}
8={131=1, 132=193, 133=443, 134=342, 135=115}
```

I just added another feature where if the value is the same no commands are executed with an option to make the delta bigger. Setting the delta makes the device less precise (delta of 1 means that when sliding only 0, 2, 4 etc are executed) but it will also mean that when the device is constantly switching between values that are very close that the Windows volume isn't constantly changed a little bit. This option can be combined with the rolling average. If the rolling average needs to be 1000ms for it to average to no difference, 500ms combined with a delta of 1 or 2 might still make it so that there still aren't any commands that are executed.
Since the range of the values seem to be 6 it might be sufficient to set the delta to 6 (even though I think that using the rolling average will still make it better).

Hopefully the combination of the added features is sufficient for you to make the sliders usable again :).

**Comment by Maddias** [comment]
Thanks, this seems to be working.
Can you also add an option to enable this feature for only sliders? The knobs don't have this issue for me.

**Comment by nvdweem** [comment]
There should be a checkbox to only apply the workarounds to the sliders now.

**Comment by Maddias** [comment]
Thanks, i think this completely fixes the issue
