### ISSUE TITLE
Discord sound not properly adjusting occasionally

### ISSUE THREAD

**Issue by AmbientWill** [nvdweem/PCPanel#7]
Hello again,

Having issues properly adjusting the volume of discord when there are multiple instances generated in the Volume mixer. It tends to just modifies one of the instances but not always. I do not know how to recreate this problem though but I do know that it happens more often when I change accounts on discord. Just bringing awareness to the fact that it does happen. Thank you!

EDIT: Using the 1.5-SNAPSHOT ATM

![image](https://user-images.githubusercontent.com/76791616/178133015-5e9c22bd-625f-4583-be2b-bf48445e1f60.png)

**Comment by nvdweem** [comment]
Discord seems to do something weird:
![image](https://user-images.githubusercontent.com/830783/178136116-2c4e7c09-bd1b-425e-9efc-cfe476f6ebeb.png)

For me, only one of the sliders is enabled, I can't change the other one. If I change my output device and then change it back it does become enabled and the PCPanel software will actually start adjusting it too... At least, sometimes:
![ChangingDiscord](https://user-images.githubusercontent.com/830783/178136607-fcd63489-532e-4302-81f4-222fe3d8ebcf.gif)
The software seems to try to change the volume but it gets set back.


When you say changing accounts, do you actually mean going into settings, logout and log back in, or do you mean switching servers? I'd expect actually changing accounts wouldn't be something that people do often.

Also, when it stops adjusting the slider, does restarting the PCPanel software resolve the issue or will it then still not adjust?
If a restart fixes it then there might be something wrong in picking up a new audio session, otherwise I have no idea what is going wrong and I'd probably have to be able to recreate the issue before being able to fix it. 
Are there any errors in the logfile (%userprofile%\.pcpanel\logs\logging.log)?

**Comment by AmbientWill** [comment]
**- If I change my output device and then change it back it does become enabled and the PCPanel software will actually start adjusting it too... At least, sometimes**
         I do see that interaction now that you mentioned it, this might be the main culprit though I'm not sure why.
         
**- When you say changing accounts, do you actually mean going into settings, logout and log back in, or do you mean switching servers? I'd expect actually changing accounts wouldn't be something that people do often.**
         The account was actually changed via settings>logout>login because I had family over that wanted to log into their account, but I agree it isn't something that would happen often.

**- If a restart fixes it then there might be something wrong in picking up a new audio session, otherwise I have no idea what is going wrong and I'd probably have to be able to recreate the issue before being able to fix it.**
         I agree that until it is repeatable, no fix can be made. I will try to recreate the issue but if it doesn't work out, its alright since changing the input/output device seems to of fixed the issue for me ATM.

**- Are there any errors in the logfile (%userprofile%.pcpanel\logs\logging.log)?**
         I see no errors upon checking the log.

So I'll close this because I can't seem to reproduce it either but the input/output device switch seemingly "fixes" the problem. Thank you for your time. I'll be sure have a reproducible issue if I post again, sorry about that.
