### ISSUE TITLE
Fatal Launch Error on Kubuntu/Pop_OS!

### ISSUE THREAD

**Issue by buttercheetah** [nvdweem/PCPanel#9]
**Describe the bug:**
After installing the application Kubuntu or Pop_OS!, the application opens for moments then seems to close itself. According to the initial logs, it was a permission issue since it installed as root, but launched under a non root user. Even after setting the permissions in /opt/pcpanel to 777 (I did try other permissions frist, but i wanted to rule out the possibility that this was just a permissions issue) the application still does not launch. 

**Steps to reproduce:**

1. install on Kubuntu or popos and attempt to launch

**Expected behavior:**

It launches.

**Additional context:**

I understand that the program was originally made for and tested on Ubuntu. However, These are forks of Ubuntu so I hoped I could get it working.
I have attached the log from my home directory /.pcpanel/logs as well as the log file from /opt/pcpanel/bi
[logging.log](https://github.com/nvdweem/PCPanel/files/9367188/logging.log)
n
[hs_err_pid10678.log](https://github.com/nvdweem/PCPanel/files/9367192/hs_err_pid10678.log)

**Comment by nvdweem** [comment]
The hs_err_pid10678.log file mentions 
`Event: 1.235 Thread 0x00007f84cc15c4f0 Exception <a 'java/lang/UnsatisfiedLinkError'{0x000000062957a660}: libhidapi.so: cannot open shared object file: No such file or directory> (0x000000062957a660) 
thrown [src/hotspot/share/prims/jni.cpp, line 535]`

The libhidapi.so is quite essential, so not being able to find it might be an issue (even though I think it's also being used to find the device and that seems to succeed according to the other log).

I'll try to make some time to install a Pop_OS! vm this weekend and see what it could be.

**Comment by nvdweem** [comment]
I installed a Pop_OS! and Kubuntu VM, it seems that I can reproduce the issue on Kubuntu and after some debugging it seems that the shortcut-profile-switching functionality broke something so that showing the application window crashed the JVM. For now I disabled that functionality which seems to fix it for me. On Kubuntu the application now seems to run correctly and it should work.

I also tried it on Pop_OS! yesterday but I there the application seemed to start correctly (but today I noticed that very rarely it would also start on Kubuntu, so perhaps I was just (un)lucky :)). I did notice that the process explorer and actually switching didn't seem to work on Pop so I'll look into that a bit further.

For now the current 1.5-SNAPSHOT version should make it work.

I also updated the readme, it seems that after installing the software it needs to be run as root the first time. I think that some of the libraries extract .so files into the install-directory which requires root access. After the initial startup, running the application seems to work fine so there should be no need to chmod the directory.

**Comment by nvdweem** [comment]
@buttercheetah: Did you have time to try the new snapshot version? If so, did it solve your issue?

**Comment by buttercheetah** [comment]
I apologize for the *very* late response. I have been using the snapshot version since you responded and it has worked perfectly on Kubuntu

**Comment by nvdweem** [comment]
Great :). I'll close the issue.
